version: '3.8'

services:
  client-service:
    build: ./client-service
    ports:
      - "8081:8080"
    networks:
      - microservices-net

  credit-service:
    build: ./credit-service
    ports:
      - "8082:8080"
    networks:
      - microservices-net

  scoring-service:
    build: ./scoring-service
    ports:
      - "8083:8080"
    networks:
      - microservices-net

  decision-service:
    build: ./decision-service
    ports:
      - "8084:8080"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
