version: '3.8'

services:
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://client-db:3306/client
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - client-db

  client-db:
    image: mysql:8.0
    container_name: client-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: client
    volumes:
      - client-db-data:/var/lib/mysql

  bareme-service:
    build:
      context: ./bareme-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bareme-db:3306/bareme
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - bareme-db

  bareme-db:
    image: mysql:8.0
    container_name: bareme-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bareme
    volumes:
      - bareme-db-data:/var/lib/mysql
  credit-service:
    build:
      context: ./credit-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://credit-db:3306/credit
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - credit-db

  credit-db:
    image: mysql:8.0
    container_name: credit-db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: credit
    volumes:
      - credit-db-data:/var/lib/mysql


  score-decision-service:
    build:
      context: ./score-decision-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://score-decision-db:3306/score
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - score-decision-db

  score-decision-db:
    image: mysql:8.0
    container_name: score-decision-db
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scoredecision
    volumes:
      - score-decision-db-data:/var/lib/mysql

  decision-service:
    build:
      context: ./decision-service
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://decision-db:3306/decision
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - decision-db

  decision-db:
    image: mysql:8.0
    container_name: decision-db
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: decision
    volumes:
      - decision-db-data:/var/lib/mysql

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8090:8080

volumes:
  client-db-data:
  bareme-db-data:
  credit-db-data:
  decision-db-data:
  score-decision-db-data: