version: '3.8'

services:
  client-service:
    build:
      context: ./client-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://client-db:3306/client
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - client-db

  client-db:
    image: mysql:8.0
    container_name: client-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: client
    volumes:
      - client-db-data:/var/lib/mysql

  bareme-service:
    build:
      context: ./bareme-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bareme-db:3306/bareme
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - bareme-db

  bareme-db:
    image: mysql:8.0
    container_name: bareme-db
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bareme
    volumes:
      - bareme-db-data:/var/lib/mysql

volumes:
  client-db-data:
  bareme-db-data:
